[project]
name = "blue"
version = "0.1.0"
description = "Retro game inspired by Celeste"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyxel>=2.3.8",
    "typing-extensions>=4.12.2",
]
